### ISSUE TITLE
MinMaxQueue, MinMaxStack

### ISSUE THREAD

**Issue by conanza** [kswang2400/data-struct#12]
I think it'd be cool if we wrote MMQ with MMS objects.

``` ruby
class MinMaxQueue
  def initialize
    @in, @out = [], []
  end

  ...
```

So instead of `@in` and `@out` being arrays, instantiate new MMStacks. Therefore, you won't have to rewrite the min/max/push/pop logic.

I think as is, `MMQ#pop` has an issue here as well.

``` ruby
  def shift
    flip! if @out.empty?

    @out.pop
  end
```

I need to write a `MMS#length`

**Comment by karenling** [comment]
You did it already!

**Comment by conanza** [comment]
sorry i got antsy. Merge it if it's good
