### ISSUE TITLE
Comment out return values or not?

### ISSUE THREAD

**Issue by karenling** [kswang2400/data-struct#14]
``` ruby
d_array = DataStruct::DynamicArray.new(4)
  => #<DynamicArray:0x007ffe5c089460 @num_items=0, @size=10, @start=0, @store=[nil, nil, nil, nil]>
```

Should we be using comments for the returns? Not sure how consistent we want to be on this or what the rules are for our readme.

**Comment by kswang2400** [comment]
i haven't been, i think i usually see the comment if its in the same line, otherwise just imitate terminal
